const state={jobType:null,kind:"Maintenance",photos:[],lib:null};
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",1400);}
function $(id){return document.getElementById(id);}
function loadLib(){if(typeof DEFAULT_LIB==="undefined"){window.DEFAULT_LIB={systems:[{id:"service-blank",name:"Service",system:"Service",equipmentHint:"",fills:[],bullets:[],extras:[]}]};}try{const raw=localStorage.getItem("halco-lib");state.lib=raw?JSON.parse(raw):structuredClone(DEFAULT_LIB);}catch(e){state.lib=structuredClone(DEFAULT_LIB);}}
function saveLib(){localStorage.setItem("halco-lib",JSON.stringify(state.lib));}
function currentSystem(){return state.lib.systems.find(s=>s.id===document.getElementById("systemSel").value)||state.lib.systems[0];}
function fillMap(){const map={};document.querySelectorAll("[data-fill]").forEach(el=>{map[el.dataset.fill]=el.value.trim();});return map;}
function applyFills(text,map){let out=text;Object.entries(map).forEach(([k,v])=>{out=out.replaceAll("{"+k+"}",v||"-");});const hsi=map.hsi?(" Tested hot surface igniter - "+map.hsi+" ohms (within range)."):"";const cap=map.cap?(" Tested capacitor - "+map.cap+"."):"";out=out.replaceAll("{hsiLine}",hsi).replaceAll("{capLine}",cap);return out.replace(/\{[a-zA-Z0-9]+\}/g,"");}
function formatDate(iso){if(!iso)return"";const p=iso.split("-");return new Date(Number(p[0]),Number(p[1])-1,Number(p[2])).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"});}
function buildNotes(){const sys=currentSystem();const map=fillMap();const date=formatDate($("jobDate").value)||formatDate(new Date().toISOString().slice(0,10));const last=$("lastName").value.trim()||"(Customer last name)";const inv=$("invoice").value.trim()||"(invoice #)";const equip=$("equipment").value.trim()||sys.equipmentHint||"(Equipment)";const extra=$("extraNotes").value.trim();const typeLine=state.jobType==="service"?"Service":(state.kind||"Maintenance");const bullets=(sys.bullets||[]).map(b=>"- "+applyFills(b,map));const extraKeep=(sys.extras||[]).map(e=>applyFills(e,map)).filter(line=>line.indexOf(": -")===-1);let body="";if(state.jobType!=="service"&&bullets.length){body+=bullets.join("\n");if(extraKeep.length)body+="\n"+extraKeep.join("\n");}if(extra)body+=(body?"\n":"")+extra;const notes=["Job Invoice Summary - "+date,last+" - "+inv,"",typeLine,equip+":",body,"","Thank you,","Jacob W"].join("\n");$("preview").textContent=notes;return notes;}
function renderFills(){const sys=currentSystem();const box=$("fillFields");box.innerHTML="";(sys.fills||[]).forEach(f=>{const lab=document.createElement("label");lab.textContent=f.label+"  ( )";const inp=document.createElement("input");inp.dataset.fill=f.key;inp.value=f.def||"";box.appendChild(lab);box.appendChild(inp);});}
function renderSystems(){const sel=$("systemSel");sel.innerHTML="";state.lib.systems.forEach(s=>{const o=document.createElement("option");o.value=s.id;o.textContent=s.name;sel.appendChild(o);});}
function showTab(name){["Job","Chat","Lib"].forEach(n=>{const pane=$("pane"+n);const btn=$("tab"+n);if(pane)pane.classList.toggle("hidden",n.toLowerCase()!==name);if(btn)btn.className=n.toLowerCase()===name?"":"ghost";});}
function addPhotos(files){[].slice.call(files).forEach(function(file){const reader=new FileReader();reader.onload=function(){state.photos.push({name:file.name,data:reader.result});drawPhotos();};reader.readAsDataURL(file);});}
function drawPhotos(){const g=$("photoGrid");if(!g)return;g.innerHTML="";state.photos.forEach(function(p,i){const img=document.createElement("img");img.src=p.data;img.onclick=function(){if(confirm("Remove this photo?")){state.photos.splice(i,1);drawPhotos();}};g.appendChild(img);});}
function helperReply(q){return "Send nameplate photos in the Grok chat. I return Model and Serial as separate copy lines.";}
function packedPrompt(){return ["Halco job notes",$("preview").textContent].join("\n");}
function onTap(el,fn){if(!el)return;el.addEventListener("click",fn);}
function init(){if($("jsFlag"))$("jsFlag").textContent="Ready";loadLib();renderSystems();renderFills();$("libEdit").value=JSON.stringify(state.lib,null,2);$("jobDate").value=new Date().toISOString().slice(0,10);document.querySelectorAll("[data-job]").forEach(function(btn){onTap(btn,function(){state.jobType=btn.dataset.job;document.querySelectorAll("[data-job]").forEach(function(b){b.classList.toggle("on",b===btn);});$("maintKindWrap").classList.toggle("hidden",state.jobType!=="maintenance");if(state.jobType==="service")$("systemSel").value="service-blank";renderFills();});});document.querySelectorAll("[data-kind]").forEach(function(btn){onTap(btn,function(){state.kind=btn.dataset.kind;document.querySelectorAll("[data-kind]").forEach(function(b){b.classList.toggle("on",b===btn);});});});$("systemSel").onchange=renderFills;onTap($("buildBtn"),function(){buildNotes();toast("Built");});onTap($("copyNotesBtn"),function(){navigator.clipboard.writeText(buildNotes());toast("Notes copied");});onTap($("mailBtn"),function(){var n=buildNotes();location.href="mailto:?subject="+encodeURIComponent(($("lastName").value||"Job")+" notes")+"&body="+encodeURIComponent(n);});$("photoInput").onchange=function(e){addPhotos(e.target.files);};onTap($("resetBtn"),function(){if(!confirm("Clear this job?"))return;["lastName","invoice","equipment","extraNotes"].forEach(function(id){$(id).value="";});$("preview").textContent="";state.photos=[];drawPhotos();});onTap($("tabJob"),function(){showTab("job");});onTap($("tabChat"),function(){showTab("chat");});onTap($("tabLib"),function(){showTab("lib");});onTap($("chatSend"),function(){var q=$("chatIn").value.trim();if(!q)return;$("chatLog").insertAdjacentHTML("beforeend","<div class='bubble me'>"+q.replace(/</g,"<")+"</div>");$("chatIn").value="";});$("packPrompt").onclick=function(){navigator.clipboard.writeText(packedPrompt());toast("Prompt copied");};$("libSave").onclick=function(){try{state.lib=JSON.parse($("libEdit").value);saveLib();renderSystems();renderFills();toast("Library saved");}catch(err){alert(err.message);}};$("libReset").onclick=function(){state.lib=structuredClone(DEFAULT_LIB);$("libEdit").value=JSON.stringify(state.lib,null,2);saveLib();renderSystems();renderFills();toast("Defaults restored");};}
init();
