const STOCK_TO="jacob@halcoenergy.com";
const state={jobType:null,kind:"Maintenance",photos:[],lib:null};
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.style.display="block";setTimeout(function(){t.style.display="none";},1400);}
function $(id){return document.getElementById(id);}
function val(id){const el=$(id);return el?el.value.trim():"";}
function setPreview(text){var el=$("preview");if(!el)return;if("value" in el)el.value=text;else el.textContent=text;}
function getPreview(){var el=$("preview");if(!el)return"";return ("value" in el?el.value:el.textContent)||"";}
function loadLib(){if(typeof DEFAULT_LIB==="undefined"){window.DEFAULT_LIB={systems:[{id:"service-blank",name:"Service",system:"Service",equipmentHint:"",fills:[],bullets:[],extras:[]}]};}try{const raw=localStorage.getItem("halco-lib");state.lib=raw?JSON.parse(raw):structuredClone(DEFAULT_LIB);}catch(e){state.lib=structuredClone(DEFAULT_LIB);}if(state.lib&&state.lib.systems){state.lib.systems.forEach(function(s){(s.fills||[]).forEach(function(f){f.def="";});});}}
function saveLib(){localStorage.setItem("halco-lib",JSON.stringify(state.lib));}
function currentSystem(){return state.lib.systems.find(function(s){return s.id===document.getElementById("systemSel").value;})||state.lib.systems[0];}
function fillMap(){const map={};document.querySelectorAll("[data-fill]").forEach(function(el){map[el.dataset.fill]=el.value.trim();});return map;}
function applyFills(text,map){var out=text;Object.entries(map).forEach(function(kv){out=out.replaceAll("{"+kv[0]+"}",kv[1]||"");});var hsi=map.hsi?(" Tested hot surface igniter - "+map.hsi+" ohms (within range)."):"";var cap=map.cap?(" Tested capacitor - "+map.cap+"."):"";out=out.replaceAll("{hsiLine}",hsi).replaceAll("{capLine}",cap);out=out.replace(/\{[a-zA-Z0-9]+\}/g,"");out=out.replace(/Inspected and replaced\s*\.?/i,"Inspected air filter.");out=out.replace(/\s{2,}/g," ").replace(/ \./g,".");return out.trim();}
function keepExtra(line){if(!line)return false;if(/:\s*$/.test(line))return false;if(/:\s*\)/.test(line))return false;if(/,\s*,/.test(line))return false;if(/CO\s*,/.test(line)&&/O2\s*,/.test(line))return false;return true;}
function formatDate(iso){if(!iso)return"";var p=iso.split("-");return new Date(Number(p[0]),Number(p[1])-1,Number(p[2])).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"});}
function addField(box,id,label,isArea){var lab=document.createElement("label");lab.textContent=label;var el=document.createElement(isArea?"textarea":"input");el.id=id;box.appendChild(lab);box.appendChild(el);}
function renderFills(){var box=$("fillFields");box.innerHTML="";if(state.jobType==="service"){addField(box,"svcFor","Service call for");addField(box,"svcFindings","Findings",true);addField(box,"svcRecs","Recommendations",true);addField(box,"svcFix","Solution / Fix",true);return;}var sys=currentSystem();(sys.fills||[]).forEach(function(f){var lab=document.createElement("label");lab.textContent=f.label+"  (leave blank to omit)";var inp=document.createElement("input");inp.dataset.fill=f.key;inp.value="";box.appendChild(lab);box.appendChild(inp);});}
function renderSystems(){var sel=$("systemSel");sel.innerHTML="";state.lib.systems.forEach(function(s){var o=document.createElement("option");o.value=s.id;o.textContent=s.name;sel.appendChild(o);});}
function jobTag(){var last=val("lastName")||"(last name)";var inv=val("invoice")||"(invoice #)";return last+" - "+inv;}
function buildServiceBody(){var parts=[];var callFor=val("svcFor");var findings=val("svcFindings");var recs=val("svcRecs");var fix=val("svcFix");var notes=val("extraNotes");if(callFor)parts.push("Service call for: "+callFor);if(findings)parts.push("Findings:\n"+findings);if(recs)parts.push("Recommendations:\n"+recs);if(fix)parts.push("Solution/Fix:\n"+fix);if(notes)parts.push("Notes:\n"+notes);return parts.join("\n\n");}
function buildNotes(){var sys=currentSystem();var map=fillMap();var date=formatDate(val("jobDate"))||formatDate(new Date().toISOString().slice(0,10));var last=val("lastName")||"(Customer last name)";var inv=val("invoice")||"(invoice #)";var equip=val("equipment")||sys.equipmentHint||"";var typeLine=state.jobType==="service"?"Service":(state.kind||"Maintenance");var body="";if(state.jobType==="service"){body=buildServiceBody();}else{var bullets=(sys.bullets||[]).map(function(b){return "- "+applyFills(b,map);}).filter(function(line){return line.replace(/^[-\s]+/,"").length;});var extraKeep=(sys.extras||[]).map(function(e){return applyFills(e,map);}).filter(keepExtra);if(bullets.length)body+=bullets.join("\n");if(extraKeep.length)body+=(body?"\n":"")+extraKeep.join("\n");var extra=val("extraNotes");if(extra)body+=(body?"\n":"")+extra;}var lines=["Job Invoice Summary - "+date,last+" - "+inv,"",typeLine];if(equip)lines.push(equip+":");if(body)lines.push(body);lines.push("");lines.push("Thank you,");lines.push("Jacob W");var notes=lines.join("\n");setPreview(notes);return notes;}
function showTab(name){["Job","Lib"].forEach(function(n){var pane=$("pane"+n);var btn=$("tab"+n);if(pane)pane.classList.toggle("hidden",n.toLowerCase()!==name);if(btn)btn.className=n.toLowerCase()===name?"":"ghost";});}
function addPhotos(files){[].slice.call(files).forEach(function(file){var reader=new FileReader();reader.onload=function(){state.photos.push({name:file.name,data:reader.result});drawPhotos();};reader.readAsDataURL(file);});}
function drawPhotos(){var g=$("photoGrid");if(!g)return;g.innerHTML="";state.photos.forEach(function(p,i){var img=document.createElement("img");img.src=p.data;img.onclick=function(){if(confirm("Remove this photo?")){state.photos.splice(i,1);drawPhotos();}};g.appendChild(img);});}
function renderStockBoxes(){var wrap=$("stockBoxes");if(!wrap)return;wrap.innerHTML="";for(var i=1;i<=10;i++){var lab=document.createElement("label");lab.textContent="Item "+i;var inp=document.createElement("input");inp.id="stock"+i;inp.placeholder="Part / item";wrap.appendChild(lab);wrap.appendChild(inp);}}
function updateStockHeader(){var h=$("stockHeader");if(h)h.textContent="Pickup for "+jobTag();}
function stockItems(){var items=[];for(var i=1;i<=10;i++){var v=val("stock"+i);if(v)items.push(v);}return items;}
function sendStockEmail(){updateStockHeader();var items=stockItems();if(!items.length){alert("Add at least one item.");return;}var email=val("stockEmail")||STOCK_TO;$("stockEmail").value=email;localStorage.setItem("halco-stock-email",email);var tag=jobTag();var body=["Truck stock pickup",tag,""].concat(items.map(function(it){return "- "+it;})).join("\n");location.href="mailto:"+encodeURIComponent(email)+"?subject="+encodeURIComponent("Truck Stock - "+tag)+"&body="+encodeURIComponent(body);}
function notesNow(){var t=getPreview().trim();if(!t||t.indexOf("Pick a type")===0)return buildNotes();return t;}
function onTap(el,fn){if(!el)return;el.addEventListener("click",fn);}
function init(){if($("jsFlag"))$("jsFlag").textContent="Ready";loadLib();renderSystems();renderFills();renderStockBoxes();$("libEdit").value=JSON.stringify(state.lib,null,2);$("jobDate").value=new Date().toISOString().slice(0,10);$("stockEmail").value=localStorage.getItem("halco-stock-email")||STOCK_TO;["lastName","invoice"].forEach(function(id){$(id).addEventListener("input",updateStockHeader);});document.querySelectorAll("[data-job]").forEach(function(btn){onTap(btn,function(){state.jobType=btn.dataset.job;document.querySelectorAll("[data-job]").forEach(function(b){b.classList.toggle("on",b===btn);});$("maintKindWrap").classList.toggle("hidden",state.jobType!=="maintenance");if(state.jobType==="service")$("systemSel").value="service-blank";renderFills();});});document.querySelectorAll("[data-kind]").forEach(function(btn){onTap(btn,function(){state.kind=btn.dataset.kind;document.querySelectorAll("[data-kind]").forEach(function(b){b.classList.toggle("on",b===btn);});});});$("systemSel").onchange=renderFills;onTap($("buildBtn"),function(){buildNotes();toast("Built");});onTap($("copyNotesBtn"),function(){navigator.clipboard.writeText(notesNow());toast("Notes copied");});onTap($("mailBtn"),function(){var n=notesNow();location.href="mailto:"+encodeURIComponent(STOCK_TO)+"?subject="+encodeURIComponent((val("lastName")||"Job")+" notes")+"&body="+encodeURIComponent(n);});onTap($("stockBtn"),function(){showTab("job");$("stockCard").classList.remove("hidden");updateStockHeader();$("stockCard").scrollIntoView({behavior:"smooth"});});onTap($("stockAdd"),sendStockEmail);$("photoInput").onchange=function(e){addPhotos(e.target.files);};onTap($("resetBtn"),function(){if(!confirm("Clear this job?"))return;["lastName","invoice","equipment","extraNotes","svcFor","svcFindings","svcRecs","svcFix"].forEach(function(id){if($(id))$(id).value="";});for(var i=1;i<=10;i++){if($("stock"+i))$("stock"+i).value="";}setPreview("");state.photos=[];drawPhotos();updateStockHeader();});onTap($("tabJob"),function(){showTab("job");});onTap($("tabLib"),function(){showTab("lib");});$("libSave").onclick=function(){try{state.lib=JSON.parse($("libEdit").value);saveLib();renderSystems();renderFills();toast("Library saved");}catch(err){alert(err.message);}};$("libReset").onclick=function(){state.lib=structuredClone(DEFAULT_LIB);$("libEdit").value=JSON.stringify(state.lib,null,2);saveLib();renderSystems();renderFills();toast("Defaults restored");};}
init();
