const state={jobType:null,kind:"Maintenance",photos:[],lib:null};
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",1400);}
function $(id){return document.getElementById(id);}
function loadLib(){if(typeof DEFAULT_LIB==="undefined"){window.DEFAULT_LIB={systems:[{id:"service-blank",name:"Service",system:"Service",equipmentHint:"",fills:[],bullets:[],extras:[]}]};}try{const raw=localStorage.getItem("halco-lib");state.lib=raw?JSON.parse(raw):structuredClone(DEFAULT_LIB);}catch(e){state.lib=structuredClone(DEFAULT_LIB);}}
function saveLib(){localStorage.setItem("halco-lib",JSON.stringify(state.lib));}
function currentSystem(){return state.lib.systems.find(s=>s.id===document.getElementById("systemSel").value)||state.lib.systems[0];}
function fillMap(){const map={};document.querySelectorAll("[data-fill]").forEach(el=>{map[el.dataset.fill]=el.value.trim();});return map;}
function applyFills(text,map){let out=text;Object.entries(map).forEach(([k,v])=>{out=out.replaceAll("{"+k+"}",v||"—");});const hsi=map.hsi?` Tested hot surface igniter — ${map.hsi} ohms (within range).`:"";const cap=map.cap?` Tested capacitor — ${map.cap}.`:"";out=out.replaceAll("{hsiLine}",hsi).replaceAll("{capLine}",cap);return out.replace(/\{[a-zA-Z0-9]+\}/g,"");}
function formatDate(iso){if(!iso)return"";const [y,m,d]=iso.split("-");return new Date(Number(y),Number(m)-1,Number(d)).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"});}
function buildNotes(){const sys=currentSystem();const map=fillMap();const date=formatDate($("jobDate").value)||formatDate(new Date().toISOString().slice(0,10));const last=$("lastName").value.trim()||"(Customer last name)";const inv=$("invoice").value.trim()||"(invoice #)";const equip=$("equipment").value.trim()||sys.equipmentHint||"(Equipment)";const extra=$("extraNotes").value.trim();const typeLine=state.jobType==="service"?"Service":(state.kind||"Maintenance");const bullets=(sys.bullets||[]).map(b=>"- "+applyFills(b,map));const extraKeep=(sys.extras||[]).map(e=>applyFills(e,map)).filter(line=>!/:\s*(—)?\s*\)/.test(line)&&!line.includes(": —,"));let body="";if(state.jobType!=="service"&&bullets.length){body+=bullets.join("\n");if(extraKeep.length)body+="\n"+extraKeep.join("\n");}if(extra)body+=(body?"\n":"")+extra;const notes=[`Job Invoice Summary - ${date}`,`${last} - ${inv}`,"",typeLine,`${equip}:`,body,"","Thank you,","Jacob W"].join("\n");$("preview").textContent=notes;localStorage.setItem("halco-last-notes",notes);return notes;}
function renderFills(){const sys=currentSystem();const box=$("fillFields");box.innerHTML="";(sys.fills||[]).forEach(f=>{const lab=document.createElement("label");lab.textContent=f.label+"  ( )";const inp=document.createElement("input");inp.dataset.fill=f.key;inp.value=f.def||"";box.appendChild(lab);box.appendChild(inp);});}
function renderSystems(){const sel=$("systemSel");sel.innerHTML="";state.lib.systems.forEach(s=>{const o=document.createElement("option");o.value=s.id;o.textContent=s.name;sel.appendChild(o);});}
function showTab(name){["Job","Chat","Lib"].forEach(n=>{const pane=$("pane"+n);const btn=$("tab"+n);if(pane)pane.classList.toggle("hidden",n.toLowerCase()!==name);if(btn)btn.className=n.toLowerCase()===name?"":"ghost";});}
function addPhotos(files){[...files].forEach(file=>{const reader=new FileReader();reader.onload=()=>{state.photos.push({name:file.name,data:reader.result});drawPhotos();};reader.readAsDataURL(file);});}
function drawPhotos(){const g=$("photoGrid");if(!g)return;g.innerHTML="";state.photos.forEach((p,i)=>{const img=document.createElement("img");img.src=p.data;img.onclick=()=>{if(confirm("Remove this photo?")){state.photos.splice(i,1);drawPhotos();}};g.appendChild(img);});}
function helperReply(q){const notes=$("preview").textContent;const lower=q.toLowerCase();if(lower.includes("short"))return"Keep the header and one short paragraph plus ( ) readings.";if(lower.includes("prepaid"))return"Prepaid vs maintenance: same bullets, only the type label changes.";if(lower.includes("nameplate")||lower.includes("serial")||lower.includes("model"))return"Send the nameplate photo in the Grok chat. I will return Model and Serial as separate copy lines for Service Titan.";return notes;}
function packedPrompt(){return ["Halco job notes","CURRENT DRAFT:",$("preview").textContent,"EXTRA:",$("extraNotes").value].join("\n");}
function onTap(el,fn){if(!el)return;let lock=false;const run=e=>{if(lock)return;lock=true;try{fn(e);}finally{setTimeout(()=>lock=false,250);}};el.addEventListener("click",run);el.addEventListener("touchend",e=>{e.preventDefault();run(e);},{passive:false});}
function init(){const flag=$("jsFlag");if(flag)flag.textContent="Ready — tap Service or Maintenance";loadLib();renderSystems();renderFills();$("libEdit").value=JSON.stringify(state.lib,null,2);$("jobDate").value=new Date().toISOString().slice(0,10);document.querySelectorAll("[data-job]").forEach(btn=>onTap(btn,()=>{state.jobType=btn.dataset.job;document.querySelectorAll("[data-job]").forEach(b=>b.classList.toggle("on",b===btn));$("maintKindWrap").classList.toggle("hidden",state.jobType!=="maintenance");if(state.jobType==="service")$("systemSel").value="service-blank";renderFills();}));document.querySelectorAll("[data-kind]").forEach(btn=>onTap(btn,()=>{state.kind=btn.dataset.kind;document.querySelectorAll("[data-kind]").forEach(b=>b.classList.toggle("on",b===btn));}));$("systemSel").onchange=renderFills;onTap($("buildBtn"),()=>{buildNotes();toast("Built");});onTap($("copyNotesBtn"),()=>{navigator.clipboard.writeText(buildNotes());toast("Notes copied");});onTap($("mailBtn"),()=>{const n=buildNotes();location.href="mailto:?subject="+encodeURIComponent(($("lastName").value||"Job")+" notes")+"&body="+encodeURIComponent(n);});$("photoInput").onchange=e=>addPhotos(e.target.files);onTap($("resetBtn"),()=>{if(!confirm("Clear this job?"))return;["lastName","invoice","equipment","extraNotes"].forEach(id=>$(
 id).value="");$("preview").textContent="";state.photos=[];drawPhotos();});onTap($("tabJob"),()=>showTab("job"));onTap($("tabChat"),()=>showTab("chat"));onTap($("tabLib"),()=>showTab("lib"));onTap($("chatSend"),()=>{const q=$("chatIn").value.trim();if(!q)return;const log=$("chatLog");log.insertAdjacentHTML("beforeend","<div class='bubble me'>"+q.replace(/</g,"<")+"</div>");log.insertAdjacentHTML("beforeend","<div class='bubble'>"+helperReply(q).replace(/</g,"<").replace(/\n/g,"<br>")+"</div>");$("chatIn").value="";});$("packPrompt").onclick=()=>{navigator.clipboard.writeText(packedPrompt());toast("Prompt copied");};$("libSave").onclick=()=>{try{state.lib=JSON.parse($("libEdit").value);saveLib();renderSystems();renderFills();toast("Library saved");}catch(err){alert(err.message);}};$("libReset").onclick=()=>{state.lib=structuredClone(DEFAULT_LIB);$("libEdit").value=JSON.stringify(state.lib,null,2);saveLib();renderSystems();renderFills();toast("Defaults restored");};}
init();
